defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: <%= ENV['GH_POSTGRESQL_PORT'] || 5432 %>
  username: <%= ENV['GH_POSTGRESQL_USER'] || ENV['USER'] %>
  min_messages: WARNING

development:
  <<: *defaults
  database: swordfish_development

test:
  <<: *defaults
  database: swordfish_test
